Repository AY2324S2-CS2103T-W13-1/tp, pull requests merged in 2024-03, with the labels that each got.

#17 Fixes #8 Jun Wei's AboutUs.md update
  docs/AboutUs.md
  docs/images/kjw142857.png
Labels: documentation

#22 Update Use Cases and NFRs in Developer Guide
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#20 Fixes #10 Edit README.md to reflect project scope
  README.md
Labels: documentation

#21 Update AboutUs.md for marcus-ny
  docs/AboutUs.md
  docs/images/marcus-ny.png
Labels: documentation

#24 Update Jekyll markdown _config.yml title to "LoanGuard Pro"
  docs/_config.yml
Labels: documentation, priority.Low

#27 Update AboutUs xiaorui-ui
  docs/AboutUs.md
  docs/images/xiaorui-ui.png
Labels: documentation

#28 Fixes #11 Update DG: Product Scope, User stories and Glossary
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#36 Fixes #3 Add Loan class and LoanRecords class.
  src/main/java/seedu/address/model/person/Loan.java
  src/main/java/seedu/address/model/person/LoanRecords.java
Labels: priority.High

#38 Integrate LoanRecords with Person class and storage mechanism
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Loan.java
  src/main/java/seedu/address/model/person/LoanRecords.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedLoan.java
  src/main/java/seedu/address/storage/JsonAdaptedLoanRecords.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High, type.Enhancement

#41 Add link loan command
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/LinkLoanCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/LinkLoanCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Loan.java
  src/main/java/seedu/address/model/person/LoanRecords.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedLoan.java
Labels: type.Story, priority.High

#45 Change "link" command to "linkloan"
  src/main/java/seedu/address/logic/commands/LinkLoanCommand.java
Labels: priority.High, type.Bug, severity.VeryLow

#40 Implement Delete Loan Command Fixes #31 and #46
  .gitignore
  src/main/java/seedu/address/logic/commands/DeleteLoanCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteLoanCommandParser.java
  src/main/java/seedu/address/model/person/LoanRecords.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Story, priority.High

#48 Fix display logic errors in DeleteLoanCommand
  src/main/java/seedu/address/logic/commands/DeleteLoanCommand.java
Labels: priority.High, type.Bug

#51 Improve error handling
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/logic/commands/DeleteLoanCommand.java
  src/main/java/seedu/address/logic/commands/LinkLoanCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Loan.java
  src/main/java/seedu/address/storage/JsonAdaptedLoan.java
Labels: priority.High, type.Bug, severity.High

#53 Implement GUI for viewloan command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ViewLoanCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/LoanListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/LoanListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#57 Fixes #54 add isReturned field to Loan class and updated storage code to save new field
  src/main/java/seedu/address/model/person/Loan.java
  src/main/java/seedu/address/model/person/LoanRecords.java
  src/main/java/seedu/address/storage/JsonAdaptedLoan.java
Labels: priority.Medium

#61 Update UI Class Diagram
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: priority.High, type.Documentation

#63 Add Returned Status to Loan GUI components
  src/main/java/seedu/address/ui/LoanCard.java
  src/main/resources/view/LoanListCard.fxml
Labels: priority.Medium, type.Enhancement

#62 Add target contact at the top of viewloan interface
  src/main/java/seedu/address/logic/commands/ViewLoanCommand.java
  src/main/java/seedu/address/ui/LoanListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/LoanListPanel.fxml
Labels: priority.Medium, type.Enhancement

#68 Update UML sequence diagram for linkloan command
  docs/diagrams/LinkLoanSequenceDiagram.puml
  docs/images/LinkLoanSequenceDiagram.png
Labels: priority.High, type.Documentation

#75 Add Delete Loan to the developer guide
  docs/DeveloperGuide.md
  docs/diagrams/AnalyticsSequenceDiagram.puml
  docs/diagrams/DeleteLoanSequenceDiagram.puml
  docs/images/AnalyticsSequenceDiagram.png
  docs/images/DeleteLoanSequenceDiagram.png
Labels: type.Documentation

#77 Update DG with implementation details for loan view GUI
  docs/DeveloperGuide.md
Labels: priority.High

#83 Add details about "linkloan" command enhancement to Developer Guide
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#86 Add analytics command
  src/main/java/seedu/address/logic/commands/AnalyticsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AnalyticsCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High
