Repository AY2324S2-CS2103T-W13-1/tp, pull requests merged in 2024-04, with the labels that each got.

#88 Loan.java: Add assert statements
  src/main/java/seedu/address/model/person/Loan.java
Labels: type.Testing

#91 Add new flag for viewloan and merge viewloans into viewloan
  src/main/java/seedu/address/logic/commands/ViewLoanCommand.java
  src/main/java/seedu/address/logic/commands/ViewLoanRelatedCommand.java
  src/main/java/seedu/address/logic/commands/ViewLoansCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ViewLoanCommandParser.java
  src/main/java/seedu/address/model/Model.java
Labels: priority.High

#94 Implement editloan command
  src/main/java/seedu/address/logic/commands/EditLoanCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditLoanCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniqueLoanList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Enhancement

#95 Implement Analytics GUI (Tab switching)
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AnalyticsCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Analytics.java
  src/main/java/seedu/address/ui/AnalyticsPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/AnalyticsPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#99 Implement analytics GUI (Part 2 - Piechart Display)
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AnalyticsCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/analytics/DashboardData.java
  src/main/java/seedu/address/model/person/UniqueLoanList.java
  src/main/java/seedu/address/ui/AnalyticsPanel.java
  src/main/resources/view/AnalyticsPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: help wanted, priority.High

#108 Implement dynamic vbox grow properties
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High

#109 Fix gap in GUI when `viewloan <index>` is called
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ViewLoanCommand.java
  src/main/java/seedu/address/logic/commands/ViewLoansCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/LoanListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/LoanListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#119 Update editloan command to correctly show error message for invalid values
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: priority.High, type.Bug, severity.Medium

#123 Replace loan value types with BigDecimals
  src/main/java/seedu/address/logic/commands/EditLoanCommand.java
  src/main/java/seedu/address/logic/commands/LinkLoanCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/analytics/DashboardData.java
  src/main/java/seedu/address/model/person/Analytics.java
  src/main/java/seedu/address/model/person/Loan.java
  src/main/java/seedu/address/model/person/UniqueLoanList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedLoan.java
  src/main/java/seedu/address/ui/AnalyticsPanel.java
  src/test/java/seedu/address/testutil/TypicalPersonsWithLoans.java
Labels: priority.Medium, type.Bug, severity.Medium

#124 Fix behaviour of edit person in loan view
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ViewLoanCommand.java
  src/main/java/seedu/address/logic/commands/ViewLoansCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: priority.High, type.Bug

#126 Add Loanee Info on viewloan command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ViewLoanCommand.java
  src/main/java/seedu/address/logic/commands/ViewLoansCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/LoanCard.java
  src/main/java/seedu/address/ui/LoanListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/LoanListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#128 Update UG
  docs/UserGuide.md
Labels: type.Chore, type.Documentation

#132 Fix stretching personList on dual panel display
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium

#186 Fail gracefully upon loan storage tampering
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Labels: type.Bug

#193 Message bugs
  src/main/java/seedu/address/logic/commands/DeleteLoanCommand.java
  src/main/java/seedu/address/logic/commands/EditLoanCommand.java
  src/main/java/seedu/address/logic/commands/LinkLoanCommand.java
  src/main/java/seedu/address/logic/commands/MarkLoanCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkLoanCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: bug.message

#197 Update DG and images
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/storage/JsonAdaptedUniqueLoanList.java
Labels: type.Documentation

#198 Add missing analytics message usage
  src/main/java/seedu/address/logic/commands/AnalyticsCommand.java
  src/main/java/seedu/address/logic/parser/AnalyticsCommandParser.java
Labels: priority.High, severity.Medium, bug.message

#196 Update analytics and active loans description in ug
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#200 Clarify behaviour of linkloan and editloan functions
  docs/UserGuide.md
Labels: priority.High, severity.Medium, type.Documentation

#201 Fix bug causing urgency to return negative values
  src/main/java/seedu/address/model/analytics/DashboardData.java
  src/main/java/seedu/address/model/person/Analytics.java
  src/main/java/seedu/address/model/person/UniqueLoanList.java
Labels: priority.High

#202 Create testcases for Analytics and DashboardData
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/analytics/DashboardData.java
  src/test/java/seedu/address/model/analytics/DashboardDataTest.java
  src/test/java/seedu/address/model/person/AnalyticsTest.java
Labels: priority.High

#208 Improve UG quality and fix cosmetic issues
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#209 Add toString tests to MarkLoanCommand, UnmarkLoanCommand and DeleteLoanCommand
  src/test/java/seedu/address/logic/commands/DeleteLoanCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkLoanCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkLoanCommandTest.java
Labels: priority.Low, type.Testing

#211 Fix incorrect assertions in DashboardData
  src/main/java/seedu/address/model/analytics/DashboardData.java
  src/test/java/seedu/address/model/analytics/DashboardDataTest.java
Labels: priority.High, severity.High

#210 Refactor GUI-related code
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ViewLoanCommand.java
  src/main/java/seedu/address/logic/commands/ViewLoansCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/analytics/DashboardData.java
  src/main/java/seedu/address/model/person/Analytics.java
  src/main/java/seedu/address/model/tabindicator/TabIndicator.java
  src/main/java/seedu/address/ui/AnalyticsPanel.java
  src/main/java/seedu/address/ui/LoanListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/person/AnalyticsTest.java
Labels: priority.High

#220 Tidy up DG
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AnalyticsSequenceDiagram.puml
  docs/images/AnalyticsSequenceDiagram.png
Labels: type.Documentation

#222 Include Planned Enhancements in DG Table of Contents
  docs/DeveloperGuide.md
Labels: priority.Low, type.Documentation

#221 Improve Javadoc comments
  src/main/java/seedu/address/logic/commands/AnalyticsCommand.java
  src/main/java/seedu/address/logic/commands/DeleteLoanCommand.java
  src/main/java/seedu/address/logic/commands/EditLoanCommand.java
  src/main/java/seedu/address/logic/commands/LinkLoanCommand.java
  src/main/java/seedu/address/logic/commands/MarkLoanCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkLoanCommand.java
  src/main/java/seedu/address/logic/commands/ViewLoanCommand.java
  src/main/java/seedu/address/logic/commands/ViewLoansCommand.java
Labels: priority.Low, type.Documentation

#223 Add tests for `JsonSerializableAddressBook`
  src/main/java/seedu/address/model/person/Person.java
  src/test/data/JsonSerializableAddressBookTest/duplicateLoanAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidLoanAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/commons/util/JsonUtilTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Labels: type.Testing
